#!/bin/bash

NAMESPACE=monitoring

kubectl apply -f ./namespace.yml

kubectl create configmap prometheus-config \
  --from-file ./config/prometheus.yml \
  --namespace $NAMESPACE

kubectl apply -f ./node-exporter/ --namespace $NAMESPACE
kubectl apply -f ./prometheus/    --namespace $NAMESPACE

kubectl rollout restart deploy/prometheus-pod --namespace $NAMESPACE
