#!/bin/bash

NAMESPACE=monitoring

kubectl create deployment \
  prometheus-pod \
  --namespace=$NAMESPACE \
  --image=prom/prometheus \
  --replicas=1 \
  --port=9090 \
  --dry-run=client \
  --output=yaml > ./prometheus/pod.yml

kubectl apply -f ./prometheus/pod.yml
