apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-pod
  name: prometheus-pod
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-pod
    spec:
      containers:
      - image: prom/prometheus
        name: prometheus
        ports:
        - containerPort: 9090
        resources: {}
status: {}
